<?php
// Generated by Zend Framework 2
return array(
    'EasyLogger\Module'                         => __DIR__ . '//Module.php',
    'EasyLogger\Helper\Utility'                 => __DIR__ . '//src/EasyLogger/Helper/Utility.php',
    'EasyLogger\Helper\File'                    => __DIR__ . '//src/EasyLogger/Helper/File.php',
    'EasyLogger\Handler\AbstractServiceManager' => __DIR__ . '//src/EasyLogger/Handler/AbstractServiceManager.php',
    'EasyLogger\Handler\Logger'                 => __DIR__ . '//src/EasyLogger/Handler/Logger.php',
);